import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { trpc } from '../utils/trpc'

const Home: NextPage = () => {
  const { data, isLoading} = trpc.useQuery(['hello']);

  if (isLoading || !data) return <div>...Loading</div>;

  return <div>{data?.greeting}</div>


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        HMFC
      </div>
    </div>
  )
}

export default Home
